version: "3.9"

services:
  client:
    container_name: client
    build:
      context: .
      dockerfile: docker/client/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/var/www
    entrypoint: ["dev.sh"]
    depends_on:
      - nginx

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./api:/var/www
    environment:
      - PHP_HOST=api
    depends_on:
      - api

  api:
    container_name: api
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    volumes:
      - ./api:/var/www
    environment:
      APP_ENV: "development"
      APP_DEBUG: "true"
      LOG_CHANNEL: "stderr"
    depends_on:
      - db

  db:
    container_name: db
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    env_file:
      - ./docker/db/development.env

volumes:
  db: